# -*- coding: utf-8 -*-
"""Advinho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VXpx-06jfei07MYkqen8QxwfUSosUOph
"""

#07 advinhe o numero

#definindo o numero
import random
numero = random.randint(1,50)

#jogo em si
while True:
 guess = int(input('Digite o numero que acha ser o certo '))
 if guess>numero :
  print('Seu numero é muito alto! tente um menor! ')
 elif guess<numero:
  print('Seu numero é muito baixo! tente um maior! ')
 else:
    print('Acertou!')
    break