# -*- coding: utf-8 -*-
"""CaixaEletronico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HK3k87rJKipgW8njC7YF2x4weNW4V3uQ
"""

#04 CONTA BANCÁRIA

#Definindo o saldo
saldo = 0
if saldo >0:
  print(f'seu saldo é de{saldo}')
else:
  print('Você não possui saldo')

#função para sacar dinheiro

def saque (quantiA):

 if quantiA < saldo:
   total = saldo - quantiA
   return total
 else:
  return print('saldo insuficiente')

#função para depositar dinheiro

def deposito(Quantia):
  quantia = int(Quantia)
  total = saldo + quantia
  return total
#caixa eletrônico
while True:
     comando = int(input(f'o que deseja fazer? 1- Consultar meu saldo  2-Realizar um saque  3-Realizar um deposito  4-Encerrar atendimento '))

     if comando == 1:
       print(saldo)
     elif comando == 2:
       quantiaS = int(input('Quanto deseja sacar? '))
       saque(quantiaS)
     elif comando ==3:
       quantiaD = int(input('Quanto deseja depositar? '))
       deposito(quantiaD)
     if comando == 4:
       print('encerrando')
       break