# -*- coding: utf-8 -*-
"""CalcularIMC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UQLeC7kwY4m6blPKNAOmtbjI73pklU1I
"""

#08 calculadora de IMC

#função que vai calcular o IMC
def cal_imc(peso,altura):
  imc = peso/(altura**2)
  return imc

#tela principal

peso = int(input('Digite seu peso '))
altura = float(input('Digite sua altura '))
imc = cal_imc(peso,altura)
print(f'seu imc é de: {imc:.2f}')