# -*- coding: utf-8 -*-
"""ConversorDeMoeda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLFNQYvg8-q_b8I4m4PzZdSnMKRSUrkn
"""

#05 CONVERSOR DE MOEDA

#definindo qual a moeda inicial, a moeda final e a quantia

moeda_atual = input('Qual a moeda inicial, Real, Euro ou Dolar? ')
moeda_futura = input('para qual moeda pretende converter? ')
quantia = int(input(f'Qual o valor da quantia que quer converter? '))

#funções de conversão

def conv_dolar(moeda,valor):
 if moeda == 'real':
  resultado = valor / 5.03
 else:
  resultado = valor * 1.06
 return resultado

def conv_real(moeda,valor):
 if moeda == 'dolar':
  resultado = valor * 5.03
 else:
  resultado = valor * 5.33
 return resultado

def conv_euro(moeda,valor):
 if moeda == 'real':
  resultado = valor / 5.33
 else:
  resultado = valor / 1.06
 return resultado

#Conversor em si

if moeda_futura == 'real':
  print(f'Seu valor em reais é de: {conv_real(moeda_futura,quantia):.2f}')
elif moeda_futura == 'dolar':
    print(f'Seu valor em dolares é de: {conv_dolar(moeda_futura,quantia):.2f}')
else:
     print(f'Seu valor em euros é de: {conv_euro(moeda_futura,quantia):.2f}')