# -*- coding: utf-8 -*-
"""JogoDaForca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZG2R5-Mt1pJMcSzWjLqP5kwTZZw75PyB
"""

#3: jogo da forca

import random
# Lista de palavras para o jogo
palavras = ["Insano", "Trouxa", "Careta", "Dilema", "Legado"]
vidas = 6
letras_adivinhadas = []

# Escolher uma palavra aleatória da lista
palavra_escolhida = random.choice(palavras)

# Função para mostrar o progresso da palavra
def mostrar_palavra(palavra, letras_adivinhadas):
    resultado = ""
    for letra in palavra:
        if letra in letras_adivinhadas:
            resultado += letra
        else:
            resultado += "_"
    return resultado

#Jogo principal
while True:
    print("\nPalavra: " + mostrar_palavra(palavra_escolhida, letras_adivinhadas))
    tentativa = input("Digite uma letra: ").lower()

    if tentativa in letras_adivinhadas:
        print("Você já tentou esta letra.")

    elif tentativa in palavra_escolhida:
        letras_adivinhadas.append(tentativa)
        if palavra_escolhida == mostrar_palavra(palavra_escolhida, letras_adivinhadas):
            print("\nParabéns! Você venceu. A palavra era:", palavra_escolhida)
            break
    else:
        letras_adivinhadas.append(tentativa)
        vidas -= 1
        print("Letra não encontrada. Você tem", vidas, "vidas restantes.")

    if vidas == 0:
        print("\nVocê perdeu. A palavra era:", palavra_escolhida)
        break