# -*- coding: utf-8 -*-
"""Media.ipy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GsbbflmKNDoruB41gq7cRmM0mIwQvWIZ
"""

#01: Calculadora da média de quatro notas

#input das notas

nota_1 = int(input('digite a primeira nota '))
nota_2 = int(input('digite a segunda nota '))
nota_3 = int(input('digite a terceira nota '))
nota_4 = int(input('digite a quarta nota '))

#calculo das médias

media = (nota_1+nota_2+nota_3+nota_4)/4
if media >= 8:
 print(f'sua média é {media}(A)')

elif media <8 and media >7:
  print(f'sua média é {media}(B)')

elif media <7 and media > 5:
 print(f'sua média é {media}(C)')

elif media <5 and media >3:
 print(f'sua média é {media}(D)')

else :
  print(f'sua média é {media}(F)')
